name: Create release drafter

on:
    push:
        branches:
            - master

permissions:
    contents: read

jobs:
    release-drafter:
        runs-on: ubuntu-latest
        permissions:
            # write permission is required to create a github release
            contents: write
            # write permission is required for autolabeler
            # otherwise, read permission is required at least
            pull-requests: write
        steps:
            - uses: release-drafter/release-drafter@v5
              with:
                  commitish: main
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
